import uuid
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import Select, func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.complaint import Complaint
from app.schemas.complaint import (
    CategoryEnum,
    ComplaintCreate,
    ComplaintResponse,
    PriorityEnum,
    StatusEnum,
    TriageResult,
)
from app.schemas.stats import StatsResponse


def _parse_uuid(value: str) -> uuid.UUID | None:
    """Malformed ids are simply not found (404) — never a database error."""
    try:
        return uuid.UUID(value)
    except (ValueError, AttributeError, TypeError):
        return None


class ComplaintRepository:
    """Repository layer owning every piece of SQL for complaints.

    A live AsyncSession is mandatory: there is deliberately no in-memory fallback,
    because a fallback would silently hide a broken database connection and make
    `docker compose down && up` appear to persist data when it does not.
    """

    async def create(
        self,
        complaint: ComplaintCreate,
        triage_result: TriageResult | None = None,
        triage_latency_ms: int | None = None,
        *,
        session: AsyncSession,
    ) -> ComplaintResponse:
        now = datetime.now(UTC)

        # Contract: status always starts at `open` (§2.3 default); triage fills
        # category/priority/summary but never advances the lifecycle. The id is
        # generated by the database (gen_random_uuid), never by the client.
        category = triage_result.category if triage_result else None
        priority = triage_result.priority if triage_result else None
        summary = triage_result.summary if triage_result else None
        triaged_by = triage_result.triaged_by if triage_result else None

        db_item = Complaint(
            title=complaint.title,
            description=complaint.description,
            location=complaint.location,
            reporter_contact=complaint.reporter_contact,
            status=StatusEnum.OPEN,
            category=category,
            priority=priority,
            summary=summary,
            triaged_by=triaged_by,
            triage_latency_ms=triage_latency_ms,
            created_at=now,
            updated_at=now,
        )
        session.add(db_item)
        await session.commit()
        await session.refresh(db_item)
        return ComplaintResponse.model_validate(db_item)

    async def get_by_id(self, complaint_id: str, session: AsyncSession) -> ComplaintResponse | None:
        uid = _parse_uuid(complaint_id)
        if uid is None:
            return None
        stmt = select(Complaint).where(Complaint.id == uid)
        result = await session.execute(stmt)
        db_item = result.scalar_one_or_none()
        return ComplaintResponse.model_validate(db_item) if db_item else None

    async def update_status(
        self,
        complaint_id: str,
        new_status: StatusEnum,
        session: AsyncSession,
    ) -> ComplaintResponse | None:
        uid = _parse_uuid(complaint_id)
        if uid is None:
            return None
        now = datetime.now(UTC)
        stmt = (
            update(Complaint)
            .where(Complaint.id == uid)
            .values(status=new_status, updated_at=now)
            .execution_options(synchronize_session="fetch")
        )
        await session.execute(stmt)
        await session.commit()
        return await self.get_by_id(complaint_id, session=session)

    async def get_stats(self, session: AsyncSession) -> StatsResponse:
        total_stmt = select(func.count(Complaint.id))
        total_res = await session.execute(total_stmt)
        total = total_res.scalar_one() or 0

        status_stmt = select(Complaint.status, func.count(Complaint.id)).group_by(Complaint.status)
        status_res = await session.execute(status_stmt)
        by_status = {s.value: count for s, count in status_res.all()}

        cat_stmt = select(Complaint.category, func.count(Complaint.id)).group_by(Complaint.category)
        cat_res = await session.execute(cat_stmt)
        by_category = {c.value if c else "UNASSIGNED": count for c, count in cat_res.all()}

        pri_stmt = select(Complaint.priority, func.count(Complaint.id)).group_by(Complaint.priority)
        pri_res = await session.execute(pri_stmt)
        by_priority = {p.value if p else "UNASSIGNED": count for p, count in pri_res.all()}

        return StatsResponse(
            total_complaints=total,
            by_status=by_status,
            by_category=by_category,
            by_priority=by_priority,
        )

    @staticmethod
    def _filtered_query(
        category: CategoryEnum | None,
        priority: PriorityEnum | None,
        status: StatusEnum | None,
    ) -> Select[Any]:
        """Single source of truth for list filters — used by both paging and counting."""
        query = select(Complaint)
        if category:
            query = query.where(Complaint.category == category)
        if priority:
            query = query.where(Complaint.priority == priority)
        if status:
            query = query.where(Complaint.status == status)
        return query

    async def count_filtered(
        self,
        category: CategoryEnum | None = None,
        priority: PriorityEnum | None = None,
        status: StatusEnum | None = None,
        *,
        session: AsyncSession,
    ) -> int:
        """Total row count for the active filters — backs the `total` field of the list contract."""
        query = self._filtered_query(category, priority, status).with_only_columns(func.count(Complaint.id))
        result = await session.execute(query)
        return result.scalar_one() or 0

    async def list_all(
        self,
        category: CategoryEnum | None = None,
        priority: PriorityEnum | None = None,
        status: StatusEnum | None = None,
        skip: int = 0,
        limit: int = 10,
        *,
        session: AsyncSession,
    ) -> list[ComplaintResponse]:
        query = (
            self._filtered_query(category, priority, status)
            .order_by(Complaint.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        result = await session.execute(query)
        db_items: Sequence[Complaint] = result.scalars().all()
        return [ComplaintResponse.model_validate(item) for item in db_items]
