"""Contract §2.3 schema conformance: DB-enforced limits, UUID ids, and new columns."""

import asyncio
import os
import uuid as uuid_lib
from datetime import datetime

import asyncpg
import pytest

from app.schemas.complaint import CategoryEnum, PriorityEnum, TriageResult


def _asyncpg_url() -> str:
    return os.environ["DATABASE_URL"].replace("postgresql+asyncpg://", "postgresql://", 1)


def test_create_returns_server_generated_uuid_and_contract_columns(client):
    payload = {
        "title": "Schema conformance smoke complaint",
        "description": "A full-length description verifying the new contract columns.",
        "location": "Sector G-10, Islamabad",
        "reporter_contact": "0300-1234567",
    }
    response = client.post("/api/complaints", json=payload)
    assert response.status_code == 201
    data = response.json()

    # id is a real UUID generated by the database, not the client
    uuid_lib.UUID(data["id"])

    # reporter_contact round-trips (nullable contract column)
    assert data["reporter_contact"] == "0300-1234567"

    # triage_latency_ms is recorded for every triage attempt
    assert isinstance(data["triage_latency_ms"], int)
    assert data["triage_latency_ms"] >= 0

    # timestamps are timezone-aware (timestamptz)
    created = datetime.fromisoformat(data["created_at"].replace("Z", "+00:00"))
    assert created.tzinfo is not None

    # ai_summary obeys the 140-char one-line contract
    if data["summary"] is not None:
        assert len(data["summary"]) <= 140
        assert "\n" not in data["summary"]


def test_malformed_id_is_404_not_500(client):
    assert client.get("/api/complaints/not-a-uuid").status_code == 404
    assert client.patch("/api/complaints/not-a-uuid/status", json={"status": "in_progress"}).status_code == 404


def test_summary_longer_than_140_chars_is_rejected_by_schema():
    with pytest.raises(Exception) as exc_info:
        TriageResult(
            category=CategoryEnum.OTHER,
            priority=PriorityEnum.LOW,
            summary="x" * 141,
            triaged_by="rules",
            confidence_score=0.5,
        )
    assert "summary" in str(exc_info.value)


def test_summary_newlines_are_flattened_to_one_line():
    result = TriageResult(
        category=CategoryEnum.OTHER,
        priority=PriorityEnum.LOW,
        summary="line one\nline two",
        triaged_by="rules",
        confidence_score=0.5,
    )
    assert result.summary == "line one line two"


def test_database_rejects_short_description_below_app_layer():
    """The contract demands 10-2000 chars enforced in the DB as well as the app.

    This INSERT bypasses Pydantic entirely: only a CHECK constraint can stop it.
    If the constraint is missing the insert succeeds and pytest.raises fails.
    """

    async def _run() -> None:
        conn = await asyncpg.connect(_asyncpg_url())
        try:
            with pytest.raises(asyncpg.exceptions.CheckViolationError):
                await conn.execute(
                    'INSERT INTO complaints (title, "text", location, status, created_at, updated_at) '
                    "VALUES ('short', 'tiny', 'Somewhere', 'open', now(), now())"
                )
        finally:
            await conn.close()

    asyncio.run(_run())


def test_database_rejects_description_longer_than_2000_chars():
    async def _run() -> None:
        conn = await asyncpg.connect(_asyncpg_url())
        try:
            with pytest.raises(asyncpg.exceptions.CheckViolationError):
                await conn.execute(
                    'INSERT INTO complaints (title, "text", location, status, created_at, updated_at) '
                    "VALUES ('long', $1, 'Somewhere', 'open', now(), now())",
                    "x" * 2001,
                )
        finally:
            await conn.close()

    asyncio.run(_run())
